### ISSUE TITLE
Configure HPA on a Gateway basis

### ISSUE THREAD

**Issue by kemv** [tv2-oss/bifrost-gateway-controller#227]
# Summary

As a user, I should be able to configure my gateways HPA (eg. set `minReplicas` the same way I configure other settings of my `Gateway`

# Motivation
To set `minReplica` of my HPA

# Proposal

By changing the relevant `GatewayClassBlueprint`, and the mechanisms that create child gateways

**Comment by michaelvl** [comment]
Isn't this what the current values listed below already does (these are part of the current blueprint)?

```
      hpa:
        minReplicas: 1  # optional
        maxReplicas: 3  # Optional, will default to minReplicas if minReplicas is defined
        averageUtilization: 60
```
